---

title: "rn3_encoding_barplot_timeavg_TFR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, include = 'false'}
library(Rmisc)
library(dplyr)
library(data.table)
library(ggplot2)
library(wesanderson)
library(gridExtra)
```

### Plot settings
```{r plot settings}

text.theme = theme(plot.title = element_text(size = 15, 
                                             hjust = 0.5, 
                                             lineheight = 1.2,
                                             family = "Helvetica Neue", 
                                             face = "bold"),
                   axis.title.x = element_text(size = 14,
                                               family = "Helvetica Neue",
                                               face = "bold"),
                   axis.title.y = element_text(size = 14,
                                               family = "Helvetica Neue",
                                               face = "bold"),
                   axis.text.x = element_text(size = 12,
                                              family = "Helvetica Neue"),
                   axis.text.y = element_text(size = 12,
                                              family = "Helvetica Neue"))


legend.theme = theme(legend.position = "bottom",
                     legend.title = element_text(size = 11,
                                                 family = "Helvetica Neue",
                                                 face = "bold"))

legend.none = theme(legend.position = "none")

color_1 = "#50b17b" # green
color_2 = "#a7d8bc" # lightgreen
color_3 = "#8C45AC" # purple
color_4 = "#D0A1E6" # lilac 

```

# Encoding cvsi performance

## Open datafile

Open the original csv files and combine for every session and participant
```{r open data perf}
path = '/Users/rosenasrawi/Documents/VU PhD/Projects/rn3 - Sequential encoding/Data/Processed/EEG/Locked encoding/timecourse average/'

# Fast - slow

filename = 'fast_slow_postenc.csv'
headername = 'header_fast_slow_postenc.csv'

fastslow = read.csv(paste(path, filename, sep = ""))
names(fastslow) = names(read.csv(paste(path, headername, sep = "")))

# Prec - imprec

filename = 'prec_imprec_postenc.csv'
headername = 'header_prec_imprec_postenc.csv'

precimprec = read.csv(paste(path, filename, sep = ""))
names(precimprec) = names(read.csv(paste(path, headername, sep = "")))

# Subs

subjects = 1:25

for (sub in 1:length(subjects)) {
  sub
  if (sub < 10) {
    subjects[sub] = paste('s0', as.character(sub), sep = "")
  } else {
    subjects[sub] = paste('s', as.character(sub), sep = "")
  }
}


```

## Summarise the data

```{r timecourse average load 2: moment x perf}

# Fast - slow

fastslow.subj.moment.perf = data.frame(row.names = 1:(length(subjects)*length(fastslow)))

fastslow.subj.moment.perf$subjectID      = rep(subjects, length(fastslow))
fastslow.subj.moment.perf$momentType     = c(rep('load-two-T1', 2*length(subjects)), rep('load-two-T2', 2*length(subjects)))
fastslow.subj.moment.perf$fastSlow       = rep(c(rep('fast', length(subjects)), rep('slow', length(subjects))),2)
fastslow.subj.moment.perf$timecourseAvg  = c(fastslow$load2.T1.fast, fastslow$load2.T1.slow, fastslow$load2.T2.fast, fastslow$load2.T2.slow)

fastslow.moment.perf = summarySE(data = fastslow.subj.moment.perf,
                                 measurevar = "timecourseAvg",
                                 groupvars = c("momentType", "fastSlow"))
fastslow.moment.perf

# Prec - imprec

precimprec.subj.moment.perf = data.frame(row.names = 1:(length(subjects)*length(fastslow)))

precimprec.subj.moment.perf$subjectID      = rep(subjects, length(precimprec))
precimprec.subj.moment.perf$momentType     = c(rep('load-two-T1', 2*length(subjects)), rep('load-two-T2', 2*length(subjects)))
precimprec.subj.moment.perf$precImprec       = rep(c(rep('prec', length(subjects)), rep('imprec', length(subjects))),2)
precimprec.subj.moment.perf$timecourseAvg  = c(precimprec$load2.T1.prec, precimprec$load2.T1.imprec, precimprec$load2.T2.prec, precimprec$load2.T2.imprec)

precimprec.moment.perf = summarySE(data = precimprec.subj.moment.perf,
                                 measurevar = "timecourseAvg",
                                 groupvars = c("momentType", "precImprec"))

precimprec.moment.perf

```

### Timecourse average: moment x perf

```{r plot DT fastslow}

ggplot(fastslow.moment.perf, 
       aes(x = momentType, y = timecourseAvg, 
           col = interaction(momentType,fastSlow), 
           fill = interaction(momentType,fastSlow), 
           group = fastSlow)) +
  
  geom_bar(stat = "identity", position = position_dodge(width = 1), 
           color = "black", width = 0.5, size = 0.4) +
  
  geom_errorbar(aes(ymin = timecourseAvg-se, ymax = timecourseAvg+se), width = 0.1, 
                position = position_dodge(1), size = 0.5, color = "black") +  
  
  geom_hline(yintercept = 0, linetype = 2) +

  scale_fill_manual(values = c(color_1, color_1, color_2, color_2))+
  
  facet_wrap(~momentType, scales = 'free_x', nrow = 2)+
  scale_y_continuous("Average motor beta post-encoding") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(-5,2)) +

  theme_classic() +
  text.theme +
  legend.none

```

```{r plot DT precimprec}

ggplot(precimprec.moment.perf, 
       aes(x = momentType, y = timecourseAvg, 
           col = interaction(momentType,precImprec), 
           fill = interaction(momentType,precImprec), 
           group = precImprec)) +
  
  geom_bar(stat = "identity", position = position_dodge(width = 1), 
           color = "black", width = 0.5, size = 0.4) +
  
  geom_errorbar(aes(ymin = timecourseAvg-se, ymax = timecourseAvg+se), width = 0.1, 
                position = position_dodge(1), size = 0.5, color = "black") +  
  
  geom_hline(yintercept = 0, linetype = 2) +

  scale_fill_manual(values = c(color_3, color_3, color_4, color_4))+
  
  facet_wrap(~momentType, scales = 'free_x', nrow = 2)+
  scale_y_continuous("Average motor beta post-encoding") +
  scale_x_discrete("Memory load") +

  coord_cartesian(ylim = c(-5,2)) +

  theme_classic() +
  text.theme +
  legend.none

```
### ANOVA: moment x perf
```{r stat moment x perf}

aov_fastslow <- aov(timecourseAvg ~ momentType * fastSlow, data = fastslow.subj.moment.perf)
summary(aov_fastslow)
TukeyHSD(aov_fastslow)

aov_precimprec <- aov(timecourseAvg ~ momentType * precImprec, data = precimprec.subj.moment.perf)
summary(aov_precimprec)
TukeyHSD(aov_precimprec)

```